# https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
decorations = "full"
# opacity = 0.6
startup_mode = "Maximized"
dynamic_title = true
padding = { x = 0, y = 0 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16


[keyboard]
bindings = [
	{ key = "C", mods = "Command", Action = "Copy" },
	{ key = "V", mods = "Command", Action = "Paste" },
]
