set-option -sa terminal-overrides ",xterm*:Tc"

# allow mouse control
set -g mouse on

# set prefix to Ctrl + A
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# 1-based index for panes and windows
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# renumber windows when windows are deleted
set-option -g renumber-windows on

# allow shift+enter to add newline
set -g extended-keys on
set -g extended-keys-format csi-u

# allow notifications to pass through from tmux to terminal
set -g allow-passthrough on

# open panes in current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Allow for faster key repetition
set -s escape-time 0

set -g @plugin 'tmux-plugins/tpm'

# List of plugins

# Sensible defaults
set -g @plugin 'tmux-plugins/tmux-sensible'

# Session switcher
set -g @plugin '27medkamal/tmux-session-wizard'

set -g @session-wizard 's'

# powerline theme
set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'everforest'


run '~/.config/tmux/plugins/tpm/tpm'
